### ISSUE TITLE
Parts list

### ISSUE THREAD

**Issue by jodi319** [evanman83/OURS-project#2]
Your parts list does not have technical descriptions; for examples the "battery charger for 18650 batteries". Is this the IP2312 ?

**Comment by Arcktosh** [comment]
Able to add a camera and some sensors?

**Comment by evanman83** [comment]
@jodi319 - the exact charger used doesn't matter, just as long as it can provide 1 amp at least. I am no expert on battery charging so it's worth experimenting. I will update the parts list to mention that it uses the TP4056 chip. My exact part was this one: https://mantech.co.za/ProductInfo.aspx?Item=15M7777.

@Arcktosh - it has GPS and a camera on it, but sure, it can definitely do with more sensors!
