### ISSUE TITLE
[SUGGESTION] Is it possible to use a phone-friendly Desktop Environment

### ISSUE THREAD

**Issue by anasouardini** [evanman83/OURS-project#6]
I've been tinkering with DEs in the past week and came across GNOME Phosh. While GNOME is already made to work with touchscreens, Phosh offers a premium experience.

As you might already know, the only tricky thing is going to be hardware support — I have not tested it on a rasp berry pi before.

Just throwing it out there; I hope I can use this project idea as a daily driver in the future.

**Comment by evanman83** [comment]
Hi there, thanks for your suggestion. We have been discussing various OSs in our Telegram group and Phosh came up as one of the strong candidate options. Our next version is using an OrangePi CM4 board with stronger specs that can run Ubuntu, so Phosh should be easy to get going. We are busy waiting for our dev boards to arrive in the mail before we can continue...

**Comment by anasouardini** [comment]
Thanks for the consideration.
Oh, Orange Pi! I can't wait.
